export const ORDER_SOURCE_OPTIONS = [
    { value: 'Прямой трафик', label: 'Прямой трафик' },
    { value: 'Google', label: 'Google' },
    { value: 'Яндекс', label: 'Яндекс' },
    { value: 'Rambler', label: 'Rambler' },
    { value: 'Яндекс.Директ', label: 'Яндекс.Директ' },
    { value: 'Бегун', label: 'Бегун' },
    { value: 'Google Adwords', label: 'Google Adwords' },
    { value: 'Яндекс.Маркет', label: 'Яндекс.Маркет' },
    { value: 'Сайты', label: 'Сайты' },
    { value: 'Mail.ru', label: 'Mail.ru' },
    { value: 'Livejournal', label: 'Livejournal' },
    { value: 'SEO', label: 'SEO' },
    { value: 'В контакте', label: 'В контакте' },
    { value: 'Почта', label: 'Почта' },
    { value: 'Приложение', label: 'Приложение' },
    { value: 'Instagram', label: 'Instagram' },
    { value: 'Youtube', label: 'Youtube' },
    { value: 'Facebook', label: 'Facebook' },
    { value: 'Одноклассники', label: 'Одноклассники' },
    { value: 'AliExpress', label: 'AliExpress' },
    { value: 'Ozon', label: 'Ozon' },
    { value: 'ВКонтакте', label: 'ВКонтакте' },
    { value: 'Wildberries', label: 'Wildberries' },
    { value: 'Sbermegamarket', label: 'Sbermegamarket' },
]

